version: "3"
services:
  postgres:
    image: "postgres:alpine"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/blog/postgres:/var/lib/postgresql/data
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/blog/nginx:/etc/nginx/conf.d
      - /var/blog/web:/var/blog/web
  blog-server:
    image: "sheason/blog-server:latest"
    restart: always
